### ISSUE TITLE
Support for osx/arm build

### ISSUE THREAD

**Issue by xiki-tempula** [conda-forge/gromacs-feedstock#18]
### Comment:

Given that apply has been supplying intel chips for many years. Might be good to have gromacs arm build for osx? Thanks.

**Comment by douglowe** [comment]
This could be difficult - currently conda-forge do not have a platform for native building of apple-silicon packages, so these have to be cross-compiled. I don't know how well the gromacs compilation process will cope with this?

**Comment by xiki-tempula** [comment]
@douglowe the M1 runner is available now https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by jan-janssen** [comment]
I opened the corresponding pull request to trigger the migration on the conda-forge side https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4990
