### ISSUE TITLE
Support for CUDA MPI build

### ISSUE THREAD

**Issue by xiki-tempula** [conda-forge/gromacs-feedstock#35]
### Comment:

So we have MPI build, we have cuda build but we don't have the cuda MPI build. I wonder why do we not have this combination? Is it like we tried to build it but failed or it is just no one bothered to do this? Thanks.

**Comment by xiki-tempula** [comment]
@mattwthompson Do you know where is cuda related thing being configured?
They are not in [recipe](https://github.com/conda-forge/gromacs-feedstock/tree/main/recipe)
/conda_build_config.yaml
or https://github.com/conda-forge/gromacs-feedstock/blob/main/recipe/meta.yaml?

**Comment by mattwthompson** [comment]
I don't know, but my best guess is that the build script is relevant

https://github.com/conda-forge/gromacs-feedstock/blob/main/recipe/build.sh

Also https://conda-forge.org/docs/maintainer/knowledge_base.html#cuda-builds
