### ISSUE TITLE
Deprecate all the osx-arm64 build except the most recent one

### ISSUE THREAD

**Issue by xiki-tempula** [conda-forge/gromacs-feedstock#47]
### Comment:

Due to this issue https://github.com/conda-forge/gromacs-feedstock/issues/44
All of the arm64 build except the most recent one (e.g. gromacs=2023.4=nompi_hf1d43a3_103) were broken. It might be good to deprecate all these builds to ensure the solver will not pick them up.

I have checked the most recent one on my M1 and it works

The list of builds that should be deprecated.

- | [osx-arm64/gromacs-2023.4-nompi_hf1d43a3_102.conda](https://anaconda.org/conda-forge/gromacs/2023.4/download/osx-arm64/gromacs-2023.4-nompi_hf1d43a3_102.conda)
- | [osx-arm64/gromacs-2023.4-nompi_hf1d43a3_101.conda](https://anaconda.org/conda-forge/gromacs/2023.4/download/osx-arm64/gromacs-2023.4-nompi_hf1d43a3_101.conda)
- | [osx-arm64/gromacs-2023.4-nompi_hf1d43a3_100.conda](https://anaconda.org/conda-forge/gromacs/2023.4/download/osx-arm64/gromacs-2023.4-nompi_hf1d43a3_100.conda)
- | [osx-arm64/gromacs-2023.4-nompi_dblprec_h79f6b9e_2.conda](https://anaconda.org/conda-forge/gromacs/2023.4/download/osx-arm64/gromacs-2023.4-nompi_dblprec_h79f6b9e_2.conda)
- | [osx-arm64/gromacs-2023.4-nompi_dblprec_h79f6b9e_1.conda](https://anaconda.org/conda-forge/gromacs/2023.4/download/osx-arm64/gromacs-2023.4-nompi_dblprec_h79f6b9e_1.conda)
- | [osx-arm64/gromacs-2023.4-nompi_dblprec_h79f6b9e_0.conda](https://anaconda.org/conda-forge/gromacs/2023.4/download/osx-arm64/gromacs-2023.4-nompi_dblprec_h79f6b9e_0.conda)
- | [osx-arm64/gromacs-2023.3-nompi_hff3e5fb_103.conda](https://anaconda.org/conda-forge/gromacs/2023.3/download/osx-arm64/gromacs-2023.3-nompi_hff3e5fb_103.conda)
- | [osx-arm64/gromacs-2023.3-nompi_hf1d43a3_104.conda](https://anaconda.org/conda-forge/gromacs/2023.3/download/osx-arm64/gromacs-2023.3-nompi_hf1d43a3_104.conda)
- | [osx-arm64/gromacs-2023.3-nompi_dblprec_h79f6b9e_4.conda](https://anaconda.org/conda-forge/gromacs/2023.3/download/osx-arm64/gromacs-2023.3-nompi_dblprec_h79f6b9e_4.conda)
- | [osx-arm64/gromacs-2023.3-nompi_dblprec_h6bd2642_3.conda](https://anaconda.org/conda-forge/gromacs/2023.3/download/osx-arm64/gromacs-2023.3-nompi_dblprec_h6bd2642_3.conda)

**Comment by mabraham** [comment]
I assume you mean to refer to all the osx-arm64 builds. I think deprecating them makes sense, but I am not sure how.

**Comment by mabraham** [comment]
Aha: https://conda-forge.org/docs/maintainer/updating_pkgs/#maint-fix-broken-packages
